### ISSUE TITLE
Yosys JS

### ISSUE THREAD

**Issue by qarlosalberto** [YoWASP/runtime-js#1]
Is there any example about how to run Yosys with node?

**Comment by whitequark** [comment]
I will add an example to https://yowasp.org soon.

**Comment by whitequark** [comment]
Done.

**Comment by qarlosalberto** [comment]
Thanks!!


I have this error in TypeScript: 

```
Cannot find module '@yowasp/yosys' or its corresponding type declarations.ts(2307)
```

**Comment by whitequark** [comment]
Version 0.37.13-dev.628 should come with TypeScript declarations.

**Comment by qarlosalberto** [comment]
Thank you very much!
